[[redirects]]
  from = "/api-test"
  to = "/api-test/overview/"
  status = 301
  force = false

[[redirects]]
  from = "/api-test/:splat/"
  to = "https://novu-api-docs.netlify.app/api/:splat/"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
