[[redirects]]
  from = "/test-api-docs"
  to = "/test-api-docs/overview/"
  status = 301
  force = false

[[redirects]]
  from = "/test-api-docs/:splat/"
  to = "https://novu-api-docs.netlify.app/api/:splat/"
  status = 200
  force = true
  headers = {X-From = "Netlify"}